language: node_js
node_js: node
deploy: 
  provider: heroku
  api_key:
    secure: Sm52jYHMtEIilDefxBGbHU775jKn4pAniQ+TA86HGCzr3R+YlTqQevIkSip0TVv9lEasBXiMfOZFFCWgP5UWM+V1kR3PJeM/M2mG4LvEIr1p1yxax+LWzZzg/NXnasZwGO0818NiqX8pmgY8UXudP0oXUh83Ys7PsOaYpqfT8ztQ1t4vvqKxK/7DKbHLwYHGoVNgSZ2V5ZEPW+Ecb6AbynehKou7VRUCokofvdhZdNohGzkN17ttHEgIqChqMxKwGjPGgFLne6/I2axLKOup1DAnV0uinr0MXVbOM7N5Q/AOO/fu7DkVPdm6xODNqhzfSyNiB2b/CRCd/BnRT68AVCg5ZWdCFlKT2VvdZt6Pd3g8O2FwkwE3LlS6OHzENIem7UtcTFqQ+ziE4CexRtgNp7+DcodjvWDlailUDSaew0i3HmjWQ8Y+wUaWkBCLSco01cluyKRaWdM24YHBy7iUs5+mPPQ1xihZDK6nlygelS6mRAuj0H7/08vvPFWdMWqUSXHEP3W7KHRBL3WGQGS0FtTqEj6sPjEB39BvitwkShXUHxo8ZY32RGnmfoKiELflKO3lENqpRSEtZjWt9DDKZpG6YNtpywBCmoRFrna3HPqA9YYsLASReuTyrFFU3FNf1iNsISBgydE1Cw2b0rCuDtZ+BDFzEl42YQ423a4X0W8=
  app: https://ancient-thicket-45987.herokuapp.com/
  on:
    repo: libbymiller09/ReadingLog

